// export {default as sum} from "simple-statistics/src/sum";
// export {default as min} from "simple-statistics/src/min";
// export {default as max} from 'simple-statistics/src/max';
// export {default as mean} from 'simple-statistics/src/mean';
// export {default as mode} from 'simple-statistics/src/mode';
// export {default as median} from 'simple-statistics/src/median';
// export {default as variance} from 'simple-statistics/src/variance';
// export {default as standardDeviation} from 'simple-statistics/src/standard_deviation';
// export {default as quantile} from 'simple-statistics/src/quantile';
export { sum, min, max, mean, mode, median, variance, standardDeviation, quantile } from 'simple-statistics';
